language: go

go:
- 1.12

go_import_path: github.com/narrowizard/nirvana-cms-auth

branches:
  only:
  - master

env:
  global:
    - secure: "fAsea5gAbqavwzudzvuiamCshBOvia9VscgBc0ZOMEz0F+so4rLm2HRVORzzwflsPGy+SVkkwVj8Lol8t5YFeKSto6JWAN5hFJwejQbbDB8rX1IwNCyz+rpmFyrDZrvzCVjs1j714G4KT48B1Vsje0OPKi5PioPl0C1hMoIfD9w2o2N3QomFZxqzqrd9oELrEpmnoRFbjtd5cJ51odyb12l6t8ILdvm1ggZid0S6mlp+BrvD5SC8hQ4OhiViBCIlO9u4DcBXLMMwbdvmEmN+ZXHyWAODv4AIep9v0PCO8XpH5GqJG2Ll3iz9eQGQa/jWxE5WKFN3w0RP3l/AyvJ1uHO8HeT7NJDyfjFo9Qk1cIEmkAJnNz1DXxa9BcfFrnqTOJl4yQvwdTptjRiruBo4b+rUxxtSwnUdiwwpGYtfGKB2BwAblYgd6obTigkwxiSbj+4dslCKXr3PtZoU4lrka4Pa1THmKcFMJ+w8oseC4Qhas5zRcMI9GhLcMlzGOUOT1uyondVvuNNZlUuXwGVGRYGHEzOlBPYvr2XfUIWEgdV20/iIAC+rG4auoYBBW0hpoK0LkSlavmcYXcvKLhYigTkxfCpUqDi6IN9bJeEbw/d5wGqYb2/xF27e2xLmf5MuCpwOnjUPhZv950OpLC2bpcT5Glb9MZ722OPF9FrGCxI="
    - secure: "0BJkaL1eG5SYPoDf79kf37UH17JQd8uXWpADjR7fLqpe62kDCDjt/UEJWheqStWDyqCBB+BiZOEeL7G+wMEemJCHtfamBrptPc8uWxZPdxOd0k7+675/LKleTxfjr8ZPUQnSsPEPtuPbPVZx3rSvasb9l0XBRqGsApQ/oETWJdGzqtRU6YH3fIgUXuolPBJl1vtUvunTvP7E3I7qgSBcq6dL2mnwe8PdJ25+1qilUHv0cAVdfEOq9gLrS0p+CqNnmv+HOMmtR5spAJL4lyxrN0vdOSRnUV8ZeqqDdOzBMvMnQkepFLFpdsiXyTT26xFabVy01OR2wwXAxgJRLKWeIRcm2u+NhiMxDG3tl2Y9X/KEUHY3f9KNZQx4akTIP3ESvttggiqOgTa0QPhS8CIlGpediTsHV/YBkn0BIwoAs9UBlKlUPUkruQKNBiE8QSMpBq6KfWOgtd+0tYFqEoaFQT13XqvLov+2Z3TvqRb8J8PXcG2AEpg0qMLWJoNDHVD94cfyt/EP8YQX8zUx9+Eyu6XjX2S3SqH2KiHXXcvW8MCdrQv6qcg0i3OtuZRgFwqQLpdstqKcTfa2l7hONkziejdd2TsRn1UHL3DjOhBj/I9JYKJzijytTFtt3u7ju1F30DGbfIO4QolmO/8X9n62pEzQz8cmvjeM3x9d1TN7xB8="
    - COMMIT=${TRAVIS_COMMIT::8}
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=narrowizard/nirvana-cms-auth
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
